# Generated by Django 6.0.3 on 2026-04-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewsexplorer', '0002_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
