# Generated by Django 6.0.3 on 2026-04-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewsexplorer', '0004_alter_comment_author_alter_comment_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='pictures',
        ),
    ]
