# Generated by Django 6.0.3 on 2026-04-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewsexplorer', '0005_rename_picture_post_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pictures',
            field=models.ManyToManyField(blank=True, related_name='posts', to='viewsexplorer.picture'),
        ),
    ]
