# Generated by Django 6.0.3 on 2026-04-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewsexplorer', '0006_alter_post_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pictures',
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ManyToManyField(related_name='posts', to='viewsexplorer.picture'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
