# Generated by Django 6.0.3 on 2026-04-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewsexplorer', '0007_remove_post_pictures_post_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='pictures',
        ),
    ]
